/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CleanEmptyLinesPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/types.ts
var DEFAULT_SETTINGS = {
  removeDuplicateEmptyLines: true,
  ensureEmptyLineBeforeHeading: true,
  ensureEmptyLineAfterHeading: true,
  emptyLineBetweenConsecutiveHeadings: true,
  removeEmptyLinesInLists: true,
  trimTrailingEmptyLines: true,
  trimLeadingEmptyLines: true,
  removeHorizontalRules: true
};

// src/cleaner.ts
var THEMATIC_BREAK_REGEX = /^[ \t]{0,3}(?:(?:-[ \t]*){3,}|(?:_[ \t]*){3,}|(?:\*[ \t]*){3,})$/;
var LIST_ITEM_REGEX = /^([ \t]*)(?:([-*+]|\d+[.)]))(?:[ \t]+(.*)|[ \t]*)$/;
var ATX_HEADING_REGEX = /^(#{1,6})(?:[ \t]+.*|[ \t]*)$/;
function getIndentSpaces(whitespace) {
  let count = 0;
  for (const ch of whitespace) {
    if (ch === "	") {
      count += 4;
    } else {
      count += 1;
    }
  }
  return count;
}
function tokenizeLines(lines) {
  var _a;
  const result = [];
  let inFrontmatter = false;
  let inCodeBlock = false;
  let codeFenceChar = "";
  let codeFenceLen = 0;
  let inMathBlock = false;
  let lastListIndent = -1;
  let inList = false;
  let hasValidFrontmatter = false;
  let frontmatterEndLine = -1;
  if (lines.length > 1 && /^---\s*$/.test(lines[0])) {
    for (let j = 1; j < lines.length; j++) {
      if (/^(?:---|\.\.\.)\s*$/.test(lines[j])) {
        hasValidFrontmatter = true;
        frontmatterEndLine = j;
        break;
      }
    }
  }
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const isBlank = /^\s*$/.test(raw);
    if (hasValidFrontmatter && i <= frontmatterEndLine) {
      result.push({ raw, isProtected: true, type: "FRONTMATTER" });
      continue;
    }
    if (inCodeBlock) {
      result.push({ raw, isProtected: true, type: "CODE_BLOCK" });
      const closeFenceRegex = new RegExp(
        `^[ ]{0,3}\\${codeFenceChar}{${codeFenceLen},}[ \\t]*$`
      );
      if (closeFenceRegex.test(raw)) {
        inCodeBlock = false;
        codeFenceChar = "";
        codeFenceLen = 0;
      }
      continue;
    } else {
      const openFenceMatch = raw.match(/^[ ]{0,3}(`{3,}|~{3,})/);
      if (openFenceMatch) {
        inCodeBlock = true;
        codeFenceChar = openFenceMatch[1][0];
        codeFenceLen = openFenceMatch[1].length;
        result.push({ raw, isProtected: true, type: "CODE_BLOCK" });
        inList = false;
        lastListIndent = -1;
        continue;
      }
    }
    if (inMathBlock) {
      result.push({ raw, isProtected: true, type: "MATH_BLOCK" });
      if (/^[ ]{0,3}\$\$\s*$/.test(raw)) {
        inMathBlock = false;
      }
      continue;
    } else {
      if (/^[ ]{0,3}\$\$\s*$/.test(raw)) {
        inMathBlock = true;
        result.push({ raw, isProtected: true, type: "MATH_BLOCK" });
        inList = false;
        lastListIndent = -1;
        continue;
      }
    }
    if (isBlank) {
      result.push({ raw: "", isProtected: false, type: "BLANK" });
      continue;
    }
    if (THEMATIC_BREAK_REGEX.test(raw)) {
      result.push({ raw, isProtected: false, type: "THEMATIC_BREAK" });
      inList = false;
      lastListIndent = -1;
      continue;
    }
    const headingMatch = raw.match(ATX_HEADING_REGEX);
    if (headingMatch) {
      const headingLevel = headingMatch[1].length;
      result.push({
        raw,
        isProtected: false,
        type: "HEADING",
        headingLevel
      });
      inList = false;
      lastListIndent = -1;
      continue;
    }
    const listMatch = raw.match(LIST_ITEM_REGEX);
    if (listMatch) {
      const leadingWhitespace = listMatch[1];
      const marker = listMatch[2];
      const indent = getIndentSpaces(leadingWhitespace);
      const isOrdered = /^\d+[.)]$/.test(marker);
      const listKind = isOrdered ? "ordered" : "unordered";
      result.push({
        raw,
        isProtected: false,
        type: "LIST_ITEM",
        listIndent: indent,
        listKind
      });
      inList = true;
      lastListIndent = indent;
      continue;
    }
    const lineIndent = getIndentSpaces(((_a = raw.match(/^(\s*)/)) == null ? void 0 : _a[1]) || "");
    if (inList && lineIndent >= 2 && lastListIndent >= 0) {
      result.push({
        raw,
        isProtected: false,
        type: "LIST_CONTINUATION",
        listIndent: lineIndent
      });
      continue;
    }
    result.push({ raw, isProtected: false, type: "TEXT" });
    inList = false;
    lastListIndent = -1;
  }
  return result;
}
function areCompatibleListItems(prev, next) {
  var _a, _b;
  if (next.type !== "LIST_ITEM") return false;
  if (prev.type !== "LIST_ITEM" && prev.type !== "LIST_CONTINUATION") return false;
  const nextIndent = (_a = next.listIndent) != null ? _a : 0;
  const prevIndent = (_b = prev.listIndent) != null ? _b : 0;
  if (nextIndent > prevIndent) return true;
  if (nextIndent < prevIndent) return true;
  if (prev.type === "LIST_ITEM") {
    return prev.listKind === next.listKind;
  }
  return true;
}
function cleanEmptyLines(content, customSettings = {}, isSelection = false) {
  if (!content) return "";
  const settings = {
    ...DEFAULT_SETTINGS,
    ...customSettings
  };
  const isCrlf = content.includes("\r\n");
  const newline = isCrlf ? "\r\n" : "\n";
  const rawLines = content.split(/\r?\n/);
  let tokens = tokenizeLines(rawLines);
  if (settings.removeHorizontalRules) {
    tokens = tokens.map((token) => {
      if (!token.isProtected && token.type === "THEMATIC_BREAK") {
        return {
          raw: "",
          isProtected: false,
          type: "BLANK"
        };
      }
      return token;
    });
  }
  if (settings.removeEmptyLinesInLists) {
    const filtered = [];
    let i = 0;
    while (i < tokens.length) {
      if (tokens[i].type === "BLANK") {
        let blankStart = i;
        let blankEnd = i;
        while (blankEnd < tokens.length && tokens[blankEnd].type === "BLANK") {
          blankEnd++;
        }
        let prevToken = null;
        for (let p = blankStart - 1; p >= 0; p--) {
          if (tokens[p].type !== "BLANK") {
            prevToken = tokens[p];
            break;
          }
        }
        let nextToken = null;
        for (let n = blankEnd; n < tokens.length; n++) {
          if (tokens[n].type !== "BLANK") {
            nextToken = tokens[n];
            break;
          }
        }
        if (prevToken && nextToken && areCompatibleListItems(prevToken, nextToken)) {
          i = blankEnd;
          continue;
        } else {
          for (let b = blankStart; b < blankEnd; b++) {
            filtered.push(tokens[b]);
          }
          i = blankEnd;
          continue;
        }
      } else {
        filtered.push(tokens[i]);
        i++;
      }
    }
    tokens = filtered;
  }
  if (settings.ensureEmptyLineBeforeHeading || settings.ensureEmptyLineAfterHeading) {
    const withHeadingSpacing = [];
    for (let i = 0; i < tokens.length; i++) {
      const current = tokens[i];
      if (current.type === "HEADING") {
        if (settings.ensureEmptyLineBeforeHeading) {
          let prevIndex = withHeadingSpacing.length - 1;
          const prev = prevIndex >= 0 ? withHeadingSpacing[prevIndex] : null;
          if (prev !== null) {
            if (prev.type === "BLANK") {
            } else if (prev.type === "HEADING") {
              if (settings.emptyLineBetweenConsecutiveHeadings) {
                withHeadingSpacing.push({
                  raw: "",
                  isProtected: false,
                  type: "BLANK"
                });
              }
            } else {
              withHeadingSpacing.push({
                raw: "",
                isProtected: false,
                type: "BLANK"
              });
            }
          }
        }
        withHeadingSpacing.push(current);
        if (settings.ensureEmptyLineAfterHeading) {
          const next = i + 1 < tokens.length ? tokens[i + 1] : null;
          if (next !== null) {
            if (next.type === "BLANK") {
            } else if (next.type === "HEADING") {
            } else {
              withHeadingSpacing.push({
                raw: "",
                isProtected: false,
                type: "BLANK"
              });
            }
          }
        }
      } else {
        withHeadingSpacing.push(current);
      }
    }
    tokens = withHeadingSpacing;
  }
  if (settings.removeDuplicateEmptyLines) {
    const collapsed = [];
    let lastWasBlank = false;
    for (const token of tokens) {
      if (token.isProtected) {
        collapsed.push(token);
        lastWasBlank = false;
      } else if (token.type === "BLANK") {
        if (!lastWasBlank) {
          collapsed.push(token);
          lastWasBlank = true;
        }
      } else {
        collapsed.push(token);
        lastWasBlank = false;
      }
    }
    tokens = collapsed;
  }
  let resultLines = tokens.map((t) => t.raw);
  if (!isSelection) {
    if (settings.trimLeadingEmptyLines) {
      while (resultLines.length > 0 && /^\s*$/.test(resultLines[0])) {
        resultLines.shift();
      }
    }
    if (settings.trimTrailingEmptyLines) {
      while (resultLines.length > 0 && /^\s*$/.test(resultLines[resultLines.length - 1])) {
        resultLines.pop();
      }
    }
  }
  let result = resultLines.join(newline);
  if (!isSelection && settings.trimTrailingEmptyLines && content.endsWith("\n") && result.length > 0) {
    result += newline;
  }
  return result;
}

// src/settings.ts
var import_obsidian = require("obsidian");
var CleanEmptyLinesSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u041D\u0430\u0441\u0442\u0440\u043E\u0439\u043A\u0438 Clean Empty Lines" });
    new import_obsidian.Setting(containerEl).setName("\u0423\u0434\u0430\u043B\u044F\u0442\u044C \u0434\u0443\u0431\u043B\u0438\u0440\u0443\u044E\u0449\u0438\u0435\u0441\u044F \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438").setDesc("\u0421\u0445\u043B\u043E\u043F\u044B\u0432\u0430\u0435\u0442 \u043D\u0435\u0441\u043A\u043E\u043B\u044C\u043A\u043E \u043F\u043E\u0434\u0440\u044F\u0434 \u0438\u0434\u0443\u0449\u0438\u0445 \u043F\u0443\u0441\u0442\u044B\u0445 \u0441\u0442\u0440\u043E\u043A \u0432 \u043E\u0434\u043D\u0443.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.removeDuplicateEmptyLines).onChange(async (value) => {
        this.plugin.settings.removeDuplicateEmptyLines = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0417\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u0438" });
    new import_obsidian.Setting(containerEl).setName("\u041F\u0443\u0441\u0442\u0430\u044F \u0441\u0442\u0440\u043E\u043A\u0430 \u043F\u0435\u0440\u0435\u0434 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u0430\u043C\u0438").setDesc("\u0413\u0430\u0440\u0430\u043D\u0442\u0438\u0440\u0443\u0435\u0442 \u043E\u0434\u043D\u0443 \u043F\u0443\u0441\u0442\u0443\u044E \u0441\u0442\u0440\u043E\u043A\u0443 \u043F\u0435\u0440\u0435\u0434 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u043E\u043C (\u043A\u0440\u043E\u043C\u0435 \u0441\u0430\u043C\u043E\u0433\u043E \u043D\u0430\u0447\u0430\u043B\u0430 \u0444\u0430\u0439\u043B\u0430).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.ensureEmptyLineBeforeHeading).onChange(async (value) => {
        this.plugin.settings.ensureEmptyLineBeforeHeading = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u041F\u0443\u0441\u0442\u0430\u044F \u0441\u0442\u0440\u043E\u043A\u0430 \u043F\u043E\u0441\u043B\u0435 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u043E\u0432").setDesc("\u0413\u0430\u0440\u0430\u043D\u0442\u0438\u0440\u0443\u0435\u0442 \u043E\u0434\u043D\u0443 \u043F\u0443\u0441\u0442\u0443\u044E \u0441\u0442\u0440\u043E\u043A\u0443 \u043F\u043E\u0441\u043B\u0435 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u0430 (\u043F\u0435\u0440\u0435\u0434 \u0441\u043B\u0435\u0434\u0443\u044E\u0449\u0438\u043C \u0442\u0435\u043A\u0441\u0442\u043E\u043C).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.ensureEmptyLineAfterHeading).onChange(async (value) => {
        this.plugin.settings.ensureEmptyLineAfterHeading = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u041F\u0443\u0441\u0442\u0430\u044F \u0441\u0442\u0440\u043E\u043A\u0430 \u043C\u0435\u0436\u0434\u0443 \u043F\u043E\u0434\u0440\u044F\u0434 \u0438\u0434\u0443\u0449\u0438\u043C\u0438 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u0430\u043C\u0438").setDesc("\u0412\u0441\u0442\u0430\u0432\u043B\u044F\u0442\u044C \u043B\u0438 \u043F\u0443\u0441\u0442\u0443\u044E \u0441\u0442\u0440\u043E\u043A\u0443 \u043C\u0435\u0436\u0434\u0443 \u0441\u043C\u0435\u0436\u043D\u044B\u043C\u0438 \u0437\u0430\u0433\u043E\u043B\u043E\u0432\u043A\u0430\u043C\u0438 (\u043D\u0430\u043F\u0440\u0438\u043C\u0435\u0440, \u043C\u0435\u0436\u0434\u0443 # \u0438 ##).").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.emptyLineBetweenConsecutiveHeadings).onChange(async (value) => {
        this.plugin.settings.emptyLineBetweenConsecutiveHeadings = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0421\u043F\u0438\u0441\u043A\u0438" });
    new import_obsidian.Setting(containerEl).setName("\u0423\u0434\u0430\u043B\u044F\u0442\u044C \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u043C\u0435\u0436\u0434\u0443 \u044D\u043B\u0435\u043C\u0435\u043D\u0442\u0430\u043C\u0438 \u0441\u043F\u0438\u0441\u043A\u0430").setDesc("\u0414\u0435\u043B\u0430\u0435\u0442 \u0441\u043F\u0438\u0441\u043A\u0438 \u043A\u043E\u043C\u043F\u0430\u043A\u0442\u043D\u044B\u043C\u0438, \u0443\u0434\u0430\u043B\u044F\u044F \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u043C\u0435\u0436\u0434\u0443 \u043F\u0443\u043D\u043A\u0442\u0430\u043C\u0438 \u0441\u043F\u0438\u0441\u043A\u043E\u0432.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.removeEmptyLinesInLists).onChange(async (value) => {
        this.plugin.settings.removeEmptyLinesInLists = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0420\u0430\u0437\u0434\u0435\u043B\u0438\u0442\u0435\u043B\u0438" });
    new import_obsidian.Setting(containerEl).setName("\u0423\u0434\u0430\u043B\u044F\u0442\u044C \u0433\u043E\u0440\u0438\u0437\u043E\u043D\u0442\u0430\u043B\u044C\u043D\u044B\u0435 \u043B\u0438\u043D\u0438\u0438 (---)").setDesc("\u0423\u0434\u0430\u043B\u044F\u0435\u0442 \u0440\u0430\u0437\u0434\u0435\u043B\u0438\u0442\u0435\u043B\u044C\u043D\u044B\u0435 \u043B\u0438\u043D\u0438\u0438 (thematic breaks / horizontal rules), \u043A\u0440\u043E\u043C\u0435 YAML frontmatter.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.removeHorizontalRules).onChange(async (value) => {
        this.plugin.settings.removeHorizontalRules = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("h3", { text: "\u0414\u043E\u043F\u043E\u043B\u043D\u0438\u0442\u0435\u043B\u044C\u043D\u043E" });
    new import_obsidian.Setting(containerEl).setName("\u0423\u0434\u0430\u043B\u044F\u0442\u044C \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0432 \u043D\u0430\u0447\u0430\u043B\u0435 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430").setDesc("\u0423\u0434\u0430\u043B\u044F\u0435\u0442 \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0432 \u0441\u0430\u043C\u043E\u043C \u0432\u0435\u0440\u0445\u0443 \u0444\u0430\u0439\u043B\u0430 \u043F\u0435\u0440\u0435\u0434 \u043F\u0435\u0440\u0432\u044B\u043C \u0441\u043E\u0434\u0435\u0440\u0436\u0438\u043C\u044B\u043C.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.trimLeadingEmptyLines).onChange(async (value) => {
        this.plugin.settings.trimLeadingEmptyLines = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u041E\u0447\u0438\u0449\u0430\u0442\u044C \u043B\u0438\u0448\u043D\u0438\u0435 \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0432 \u043A\u043E\u043D\u0446\u0435 \u0434\u043E\u043A\u0443\u043C\u0435\u043D\u0442\u0430").setDesc("\u0423\u0434\u0430\u043B\u044F\u0435\u0442 \u043B\u0438\u0448\u043D\u0438\u0435 \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0432 \u0441\u0430\u043C\u043E\u043C \u043A\u043E\u043D\u0446\u0435 \u0444\u0430\u0439\u043B\u0430.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.trimTrailingEmptyLines).onChange(async (value) => {
        this.plugin.settings.trimTrailingEmptyLines = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var CleanEmptyLinesPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.settings = DEFAULT_SETTINGS;
  }
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("list-checks", "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438", () => {
      const activeView = this.app.workspace.getActiveViewOfType(import_obsidian2.MarkdownView);
      if (activeView) {
        this.formatEditor(activeView.editor);
      } else {
        new import_obsidian2.Notice("\u041D\u0435\u0442 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0439 Markdown-\u0437\u0430\u043C\u0435\u0442\u043A\u0438");
      }
    });
    this.addCommand({
      id: "clean-empty-lines-note",
      name: "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0432 \u0430\u043A\u0442\u0438\u0432\u043D\u043E\u0439 \u0437\u0430\u043C\u0435\u0442\u043A\u0435",
      editorCallback: (editor) => {
        this.formatEditor(editor);
      }
    });
    this.addCommand({
      id: "clean-empty-lines-selection",
      name: "\u041E\u0447\u0438\u0441\u0442\u0438\u0442\u044C \u043F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0432 \u0432\u044B\u0434\u0435\u043B\u0435\u043D\u043D\u043E\u043C \u0444\u0440\u0430\u0433\u043C\u0435\u043D\u0442\u0435",
      editorCallback: (editor) => {
        this.formatSelection(editor);
      }
    });
    this.addSettingTab(new CleanEmptyLinesSettingTab(this.app, this));
  }
  formatEditor(editor) {
    const originalContent = editor.getValue();
    const cleanedContent = cleanEmptyLines(originalContent, this.settings, false);
    if (originalContent !== cleanedContent) {
      const cursor = editor.getCursor();
      editor.setValue(cleanedContent);
      const totalLines = editor.lineCount();
      editor.setCursor({
        line: Math.min(cursor.line, totalLines - 1),
        ch: cursor.ch
      });
      new import_obsidian2.Notice("\u041F\u0443\u0441\u0442\u044B\u0435 \u0441\u0442\u0440\u043E\u043A\u0438 \u0443\u0441\u043F\u0435\u0448\u043D\u043E \u043E\u0442\u0444\u043E\u0440\u043C\u0430\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u044B");
    } else {
      new import_obsidian2.Notice("\u0424\u043E\u0440\u043C\u0430\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u043D\u0435 \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F");
    }
  }
  formatSelection(editor) {
    if (!editor.somethingSelected()) {
      new import_obsidian2.Notice("\u0421\u043D\u0430\u0447\u0430\u043B\u0430 \u0432\u044B\u0434\u0435\u043B\u0438\u0442\u0435 \u0442\u0435\u043A\u0441\u0442 \u0434\u043B\u044F \u0444\u043E\u0440\u043C\u0430\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F");
      return;
    }
    const selection = editor.getSelection();
    const cleanedSelection = cleanEmptyLines(selection, this.settings, true);
    if (selection !== cleanedSelection) {
      editor.replaceSelection(cleanedSelection);
      new import_obsidian2.Notice("\u0412\u044B\u0434\u0435\u043B\u0435\u043D\u043D\u044B\u0439 \u0444\u0440\u0430\u0433\u043C\u0435\u043D\u0442 \u043E\u0442\u0444\u043E\u0440\u043C\u0430\u0442\u0438\u0440\u043E\u0432\u0430\u043D");
    } else {
      new import_obsidian2.Notice("\u0412 \u0432\u044B\u0434\u0435\u043B\u0435\u043D\u0438\u0438 \u0444\u043E\u0440\u043C\u0430\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u0435 \u043D\u0435 \u0442\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044F");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
